-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 17:58:11 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Baza_NismoSmislili
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Baza_NismoSmislili
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Baza_NismoSmislili` DEFAULT CHARACTER SET cp1250 COLLATE cp1250_croatian_ci ;
USE `Baza_NismoSmislili` ;

-- -----------------------------------------------------
-- Table `Baza_NismoSmislili`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Baza_NismoSmislili`.`users` ;

CREATE TABLE IF NOT EXISTS `Baza_NismoSmislili`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `level` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;

INSERT INTO `users` (`username`, `password`, `level`) VALUES
('admin', '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918', 2),
('testman', 'a52d744c4e56b4de0b897ef7e3c2d19be2bc8ceff8b1fbdacf8cbfb8770f1e74', 1);



-- -----------------------------------------------------
-- Table `Baza_NismoSmislili`.`Anketa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Baza_NismoSmislili`.`Anketa` ;

CREATE TABLE IF NOT EXISTS `Baza_NismoSmislili`.`Anketa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(45) NULL,
  `naziv` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Baza_NismoSmislili`.`Pitanja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Baza_NismoSmislili`.`Pitanja` ;

CREATE TABLE IF NOT EXISTS `Baza_NismoSmislili`.`Pitanja` (
  `idPitanje` INT NOT NULL,
  `idAnketa` INT NOT NULL,
  `PitanjeText` VARCHAR(45) NOT NULL,
  `RedniBroj` INT NOT NULL,
  `PitanjeOdg` VARCHAR(45) NOT NULL,
  `VrstaOdg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPitanje`),
  INDEX `fk_Pitanja_Anketa_idx` (`idAnketa` ASC),
  CONSTRAINT `fk_Pitanja_Anketa`
    FOREIGN KEY (`idAnketa`)
    REFERENCES `Baza_NismoSmislili`.`Anketa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Baza_NismoSmislili`.`PonudeniOdgovori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Baza_NismoSmislili`.`PonudeniOdgovori` ;

CREATE TABLE IF NOT EXISTS `Baza_NismoSmislili`.`PonudeniOdgovori` (
  `idOdg` INT NOT NULL AUTO_INCREMENT,
  `idPitanje` INT NOT NULL,
  `OdgovorText` VARCHAR(45) NOT NULL,
  `RedniBroj` INT NOT NULL,
  `VrstaOdg` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOdg`),
  INDEX `fk_PonudeniOdgovori_Pitanja1_idx` (`idPitanje` ASC),
  CONSTRAINT `fk_PonudeniOdgovori_Pitanja1`
    FOREIGN KEY (`idPitanje`)
    REFERENCES `Baza_NismoSmislili`.`Pitanja` (`idPitanje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
